### PR TITLE
es6 changes for JS code and some code cleanups

### PR DESCRIPTION
**Pull request by yuvarajvemula**
I have made some changes to your JavaScript code that changes includes es6 arrow functions , and new standard lexical variable declarations such as const and let to improve code quality.. and some code corrections (Semi colon missed in end of some JS files );

> **Please review and test the code to ensure that code is working as expected.**
> (please check es6 feature compatibility before testing.. and use latest Nodejs , Google chrome or Firefox.. because .. currently these browser vendors  only offering better support for latest standards of JavaScript in their JS engines  )

### CODE REVIEW

**Comment by RamuRChenchaiah** [comment]
Thank you very much
Will review & merge

Sent from my Windows Phone

**Comment by yuvarajvemula** [comment]
:+1:     :wink:

**Comment by RamuRChenchaiah** [comment]
Hi Shivraj,

I have merged the changes into new branch "es6test". Please continue with your changes in that branch.

Regards,
Ramu

**Comment by yuvarajvemula** [comment]
Thanks a lot :blush:

**Pull request closed without merging**
